[package]
name = "ru_shell"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2"    # 命令终端多彩显示
chrono = "0.4"   # 时间日期
users = "0.11.0"
libc = "0.2.151"
